services:
  home-index-scrape:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: home-index-scrape
    environment:
      - DEBUG=True
      - TIKA_SERVER_ENDPOINT=http://tika:9998
      - TIKA_CLIENT_ONLY=True
      - TZ=America/Los_Angeles
      - WAIT_FOR_DEBUGPY_CLIENT=True
    ports:
      - '5678:5678' # debugpy
    restart: unless-stopped
    volumes:
      - ./bind-mounts/files:/files
  meilisearch:
    container_name: meilisearch
    environment:
      - MEILI_NO_ANALYTICS=true
      - TZ=America/Los_Angeles
    image: getmeili/meilisearch:latest
    restart: unless-stopped
    volumes:
      - ./bind-mounts/meilisearch:/meili_data
  home-index:
    build:
      context: https://github.com/nashspence/home-index.git
      dockerfile: Dockerfile
    container_name: home-index
    depends_on:
      - meilisearch
      - home-index-scrape
    environment:
      - MODULES=http://home-index-scrape:9000
      - MEILISEARCH_HOST=http://meilisearch:7700
      - TZ=America/Los_Angeles
      - DEBUG=True
    restart: unless-stopped
    volumes:
      - ./bind-mounts/files:/files
      - ./bind-mounts/home-index:/home-index
  tika:
    command: [ "--config", "/config/tika-config.xml" ]
    container_name: tika
    environment:
      - TZ=America/Los_Angeles
    expose:
      - '9998'
    image: apache/tika:latest-full
    restart: unless-stopped
    volumes:
      - ./bind-mounts/tika:/config
      - ./bind-mounts/files:/files:ro
