---
networks:
  debug-net:
    ipam:
      driver: default
      config:
        - subnet: 172.34.0.0/24

services:
  home-index-scrape-module:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: home-index-scrape-module
    environment:
      - TIKA_HOST=http://tika:9998
      - TZ=America/Los_Angeles
      - WAIT_FOR_DEBUG_CLIENT
    ports:
      - '5678:5678' # debugpy
    restart: unless-stopped
    volumes:
      - ./bind-mounts/home-index:/storage
      - /home/ns/shared:/files
    networks:
      debug-net:
        ipv4_address: 172.34.0.10
  meilisearch:
    container_name: meilisearch
    environment:
      - MEILI_NO_ANALYTICS=true
      - TZ=America/Los_Angeles
    image: getmeili/meilisearch:latest
    restart: unless-stopped
    volumes:
      - ./bind-mounts/meilisearch:/meili_data
    networks:
      - debug-net
  home-index:
    build:
      context: https://github.com/nashspence/home-index.git
      dockerfile: Dockerfile
    container_name: home-index
    depends_on:
      - meilisearch
      - home-index-transcribe-module
    environment:
      - MODULES=http://home-index-scrape-module:9000
      - MEILISEARCH_HOST=http://meilisearch:7700
      - TZ=America/Los_Angeles
    restart: unless-stopped
    volumes:
      - ./bind-mounts/home-index:/storage
      - /home/ns/shared:/files
    networks:
      - debug-net
  tika:
    command: ["--config", "/config/tika-config.xml"]
    container_name: tika
    environment:
      - TZ=America/Los_Angeles
    expose:
      - '9998'
    image: apache/tika:latest-full
    restart: unless-stopped
    volumes:
      - ./bind-mounts/tika:/config
      - /home/ns/shared:/files:ro
    networks:
      - debug-net